name: Client Tests

on:
  push:
    branches: [ alpha, beta, rc, main ]
  pull_request:
    types: [ opened, synchronize ]
    branches: [ alpha, beta, rc, main ]

jobs:
  test-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run Client tests
        run: npm run test:shared
